/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PokeMaker;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import javax.swing.JOptionPane;

/**
 *
 * @author Wojtek
 */
public class PokeMaker extends javax.swing.JFrame {

    /**
     * Creates new form PokeMaker
     */
    TypeChecker typeCheck;
    MoveDex movedex;
    String[] conditions = new String[]{"Level", "Trade", "Trade for a Pokemon",
        "Happiness", "Weather", "Stone", "Location", "Pokemon in the party", "Ability", "Move"};

    Pokedex index;
    MoveCreator movemaker;

    public PokeMaker() {
        initComponents();
        typeCheck = new TypeChecker();
        movedex = new MoveDex();
        movemaker = new MoveCreator(movedex);
        index = new Pokedex(this);
        try {
            index.loadList("save.txt");
        } catch (Exception e) {
            System.out.println("ERROR " + e.toString());
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpriteBt = new javax.swing.JButton();
        TypeCalcBt = new javax.swing.JButton();
        SaveBt = new javax.swing.JButton();
        SpriteBt1 = new javax.swing.JButton();
        StatsP = new StatMeter();
        jLabel7 = new javax.swing.JLabel();
        NameTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TypeACB = new javax.swing.JComboBox();
        TypeBCB = new javax.swing.JComboBox();
        TypeCCB = new javax.swing.JComboBox();
        HPSp = new javax.swing.JSpinner();
        DefSp = new javax.swing.JSpinner();
        AtkSp = new javax.swing.JSpinner();
        SpdSp = new javax.swing.JSpinner();
        SpaSp = new javax.swing.JSpinner();
        SpeSp = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AbilityACB = new javax.swing.JComboBox();
        AbilityBCB = new javax.swing.JComboBox();
        AbilityHCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SpeciesTF = new javax.swing.JTextField();
        DeepStatsP = new javax.swing.JPanel();
        BaseExpSp = new javax.swing.JSpinner();
        HPEVSp = new javax.swing.JSpinner();
        AtkEVSp = new javax.swing.JSpinner();
        DefEVSp = new javax.swing.JSpinner();
        SpaEVSp = new javax.swing.JSpinner();
        SpdEVSp = new javax.swing.JSpinner();
        SpeEVSp = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CptRtSp = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        GrwRtCB = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        MaleChanceSp = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        EggNmbSp = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        ItemCB = new javax.swing.JComboBox();
        ItemPrctSp = new javax.swing.JSpinner();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        EggGrACB = new javax.swing.JComboBox();
        EggGrBCB = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        EvolveCB = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        ConditionCB = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        EvolveLevelCB = new javax.swing.JSpinner();
        CondThingL = new javax.swing.JLabel();
        EvolveThingCB = new javax.swing.JComboBox();
        GendLessCB = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescrTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        DescrTwoTA = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        AltFormCB = new javax.swing.JCheckBox();
        PokemonFormCB = new javax.swing.JComboBox();
        PokeLabelTF = new javax.swing.JTextField();
        NewBt = new javax.swing.JButton();
        NumTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        MoveMakerBt = new javax.swing.JButton();
        PokeListCB = new javax.swing.JComboBox();
        LoadBt = new javax.swing.JButton();
        DeleteBt = new javax.swing.JButton();
        SortBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        SpriteBt.setBackground(new java.awt.Color(255, 255, 255));
        SpriteBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/172.png"))); // NOI18N
        SpriteBt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SpriteBt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TypeCalcBt.setText("Type Calc");
        TypeCalcBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeCalcBtActionPerformed(evt);
            }
        });

        SaveBt.setText("Save");
        SaveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtActionPerformed(evt);
            }
        });

        SpriteBt1.setBackground(new java.awt.Color(255, 255, 255));
        SpriteBt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/172 (1).png"))); // NOI18N
        SpriteBt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SpriteBt1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        StatsP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Name:");

        jLabel9.setText("Type:");

        TypeACB.setModel(new javax.swing.DefaultComboBoxModel(typeCheck.type));

        TypeBCB.setModel(new javax.swing.DefaultComboBoxModel(typeCheck.type));

        TypeCCB.setModel(new javax.swing.DefaultComboBoxModel(typeCheck.type));

        HPSp.setValue(100);
        HPSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PokeMaker.this.stateChanged(evt);
            }
        });

        DefSp.setValue(100);
        DefSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PokeMaker.this.stateChanged(evt);
            }
        });

        AtkSp.setValue(100);
        AtkSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PokeMaker.this.stateChanged(evt);
            }
        });

        SpdSp.setValue(100);
        SpdSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PokeMaker.this.stateChanged(evt);
            }
        });

        SpaSp.setValue(100);
        SpaSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PokeMaker.this.stateChanged(evt);
            }
        });

        SpeSp.setValue(100);
        SpeSp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                PokeMaker.this.stateChanged(evt);
            }
        });

        jLabel1.setText("HP:");

        jLabel3.setText("Def:");

        jLabel2.setText("Atk:");

        jLabel4.setText("SpA:");

        jLabel5.setText("SpD:");

        jLabel6.setText("Spe:");

        AbilityACB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AbilityBCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AbilityHCB.setBackground(new java.awt.Color(255, 255, 204));
        AbilityHCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Ability:");

        jLabel10.setText("Hidden:");

        jLabel11.setText("Species:");

        javax.swing.GroupLayout StatsPLayout = new javax.swing.GroupLayout(StatsP);
        StatsP.setLayout(StatsPLayout);
        StatsPLayout.setHorizontalGroup(
            StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AbilityHCB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HPSp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(StatsPLayout.createSequentialGroup()
                        .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AtkSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DefSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SpaSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(StatsPLayout.createSequentialGroup()
                                    .addComponent(TypeACB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(TypeBCB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(SpeSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                                .addComponent(SpdSp, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TypeCCB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StatsPLayout.createSequentialGroup()
                        .addComponent(AbilityACB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AbilityBCB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(NameTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                        .addComponent(SpeciesTF, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatsPLayout.setVerticalGroup(
            StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(NameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(SpeciesTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeACB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeBCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TypeCCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HPSp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AtkSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DefSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpaSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpdSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpeSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbilityACB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AbilityBCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AbilityHCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DeepStatsP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BaseExpSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 500, 1));

        HPEVSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        AtkEVSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        DefEVSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        SpaEVSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        SpdEVSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        SpeEVSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 3, 1));

        jLabel12.setText("Base Exp:");

        jLabel13.setText("EV:");

        CptRtSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 255, 1));

        jLabel14.setText("Cpt. Rate:");

        GrwRtCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setText("Grw. Rate:");

        MaleChanceSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jLabel16.setText("Gender:");

        jLabel17.setText("% - Male");

        EggNmbSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));

        jLabel18.setText("Egg Nmb:");

        ItemCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ItemPrctSp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jLabel19.setText("%");

        jLabel20.setText("Item:");

        EggGrACB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        EggGrBCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel22.setText("Egg Group:");

        jLabel23.setText("Evolves from:");

        EvolveCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel26.setText("Condition:");

        ConditionCB.setModel(new javax.swing.DefaultComboBoxModel(conditions));
        ConditionCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConditionCBActionPerformed(evt);
            }
        });

        jLabel24.setText("Level:");

        EvolveLevelCB.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        CondThingL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        CondThingL.setText("Item:");

        EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        GendLessCB.setText("Genderless");
        GendLessCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GendLessCBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DeepStatsPLayout = new javax.swing.GroupLayout(DeepStatsP);
        DeepStatsP.setLayout(DeepStatsPLayout);
        DeepStatsPLayout.setHorizontalGroup(
            DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeepStatsPLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DeepStatsPLayout.createSequentialGroup()
                        .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DeepStatsPLayout.createSequentialGroup()
                                .addComponent(EggGrACB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EggGrBCB, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(DeepStatsPLayout.createSequentialGroup()
                                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DeepStatsPLayout.createSequentialGroup()
                                        .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(DeepStatsPLayout.createSequentialGroup()
                                                    .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(CptRtSp)
                                                        .addGroup(DeepStatsPLayout.createSequentialGroup()
                                                            .addComponent(HPEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(AtkEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(BaseExpSp))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(DefEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(GrwRtCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(DeepStatsPLayout.createSequentialGroup()
                                                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(EggNmbSp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                                    .addComponent(MaleChanceSp, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel17)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GendLessCB)
                                            .addGroup(DeepStatsPLayout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(SpaEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SpdEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(SpeEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10))
                                    .addGroup(DeepStatsPLayout.createSequentialGroup()
                                        .addComponent(ItemCB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ItemPrctSp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jLabel19)
                                .addContainerGap(24, Short.MAX_VALUE))))
                    .addGroup(DeepStatsPLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel26)
                            .addGroup(DeepStatsPLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EvolveLevelCB, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConditionCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DeepStatsPLayout.createSequentialGroup()
                                .addComponent(CondThingL, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EvolveThingCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(EvolveCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        DeepStatsPLayout.setVerticalGroup(
            DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeepStatsPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(EvolveCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(ConditionCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(EvolveLevelCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CondThingL)
                    .addComponent(EvolveThingCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BaseExpSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HPEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AtkEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DefEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpaEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpdEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpeEVSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CptRtSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrwRtCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaleChanceSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(GendLessCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EggNmbSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EggGrACB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EggGrBCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ItemCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DeepStatsPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ItemPrctSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        DescrTA.setColumns(20);
        DescrTA.setLineWrap(true);
        DescrTA.setRows(5);
        jScrollPane1.setViewportView(DescrTA);

        DescrTwoTA.setColumns(20);
        DescrTwoTA.setLineWrap(true);
        DescrTwoTA.setRows(5);
        jScrollPane2.setViewportView(DescrTwoTA);

        jLabel21.setText("Description:");

        AltFormCB.setText("Alternative Form of:");
        AltFormCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AltFormCBActionPerformed(evt);
            }
        });

        PokemonFormCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        PokemonFormCB.setToolTipText("");
        PokemonFormCB.setEnabled(false);
        PokemonFormCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PokemonFormCBActionPerformed(evt);
            }
        });

        PokeLabelTF.setFont(new java.awt.Font("MS UI Gothic", 0, 13)); // NOI18N
        PokeLabelTF.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PokeLabelTF.setText("---New---");
        PokeLabelTF.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED), javax.swing.BorderFactory.createEtchedBorder()));
        PokeLabelTF.setFocusable(false);

        NewBt.setText("New");
        NewBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewBtActionPerformed(evt);
            }
        });

        NumTF.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NumTF.setText("1");
        NumTF.setMaximumSize(new java.awt.Dimension(6, 22));

        jLabel25.setText("#");

        MoveMakerBt.setText("Move Maker");
        MoveMakerBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveMakerBtActionPerformed(evt);
            }
        });

        PokeListCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LoadBt.setText("Load");
        LoadBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadBtActionPerformed(evt);
            }
        });

        DeleteBt.setText("Delete");
        DeleteBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtActionPerformed(evt);
            }
        });

        SortBt.setText("Sort");
        SortBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PokeLabelTF, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NumTF, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel21))
                            .addComponent(SpriteBt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SpriteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TypeCalcBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MoveMakerBt))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(SaveBt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(NewBt)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(PokeListCB, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(StatsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AltFormCB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PokemonFormCB, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DeepStatsP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LoadBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SortBt))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AltFormCB)
                    .addComponent(PokemonFormCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PokeLabelTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SpriteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpriteBt1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DeepStatsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatsP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SaveBt)
                            .addComponent(NewBt)
                            .addComponent(PokeListCB)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(LoadBt)
                                .addComponent(DeleteBt)
                                .addComponent(SortBt))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeCalcBt)
                    .addComponent(MoveMakerBt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeCalcBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeCalcBtActionPerformed
        typeCheck.setVisible(true);
    }//GEN-LAST:event_TypeCalcBtActionPerformed

    private void stateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stateChanged
        javax.swing.JSpinner me = (javax.swing.JSpinner) evt.getSource();

        if (me.getValue().hashCode() > 255) {
            me.setValue(255);
        }
        if (me.getValue().hashCode() < 0) {
            me.setValue(0);
        }
        this.repaint();
    }//GEN-LAST:event_stateChanged

    private void ConditionCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConditionCBActionPerformed
        String cond = (String) ConditionCB.getSelectedItem();
        switch (cond) {
            case "Level":
            case "Trade":
            case "Happiness":
                CondThingL.setText("Item:");
                //EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
                break;
            case "Trade for a Pokemon":
            case "Pokemon in the party":
                CondThingL.setText("Pokemon:");
                //EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
                break;
            case "Weather":
                CondThingL.setText("Weather:");
                //EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
                break;
            case "Location":
                CondThingL.setText("Location:");
                //EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
                break;
            case "Stone":
                CondThingL.setText("Stone:");
                //EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
                break;
            case "Ability":
                CondThingL.setText("Ability:");
                EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new Object[]{AbilityACB.getSelectedItem(),
                    AbilityBCB.getSelectedItem(), AbilityHCB.getSelectedItem()}));
                break;
            case "Move":
                CondThingL.setText("Move:");
                //EvolveThingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[]{""}));
                break;
        }
    }//GEN-LAST:event_ConditionCBActionPerformed

    private void SaveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtActionPerformed
        index.addPokemon(new PokemonBase(
                Integer.parseInt(NumTF.getText()),
                NameTF.getText(),
                SpeciesTF.getText(),
                new String[]{TypeACB.getSelectedItem().toString(), TypeBCB.getSelectedItem().toString(), TypeCCB.getSelectedItem().toString()},
                new int[]{HPSp.getValue().hashCode(), AtkSp.getValue().hashCode(), DefSp.getValue().hashCode(),
                    SpaSp.getValue().hashCode(), SpdSp.getValue().hashCode(), SpeSp.getValue().hashCode()},
                new Object[]{AbilityACB.getSelectedItem(), AbilityBCB.getSelectedItem(), AbilityHCB.getSelectedItem()},
                EvolveCB.getSelectedItem(),
                ConditionCB.getSelectedItem().toString(),
                EvolveLevelCB.getValue().hashCode(),
                EvolveThingCB.getSelectedItem(),
                BaseExpSp.getValue().hashCode(),
                new int[]{HPEVSp.getValue().hashCode(), AtkEVSp.getValue().hashCode(), DefEVSp.getValue().hashCode(),
                    SpaEVSp.getValue().hashCode(), SpdEVSp.getValue().hashCode(), SpeEVSp.getValue().hashCode()},
                CptRtSp.getValue().hashCode(),
                GrwRtCB.getSelectedItem(),
                GendLessCB.isSelected() ? -1 : MaleChanceSp.getValue().hashCode(),
                EggNmbSp.getValue().hashCode(),
                new Object[]{EggGrACB.getSelectedItem(), EggGrBCB.getSelectedItem()},
                ItemCB.getSelectedItem(),
                ItemPrctSp.getValue().hashCode(),
                new String[]{DescrTA.getText(), DescrTwoTA.getText()},
                AltFormCB.isSelected() ? PokemonFormCB.getSelectedItem() : null));
        PokeLabelTF.setText(NameTF.getText());
        this.repaint();
    }//GEN-LAST:event_SaveBtActionPerformed

    private void AltFormCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltFormCBActionPerformed
        if (AltFormCB.isSelected()) {
            PokemonFormCB.setEnabled(true);
            PokemonBase temp = (PokemonBase) PokemonFormCB.getSelectedItem();
            if (PokemonFormCB.getSelectedIndex() != 0) {
                NumTF.setText(temp.getIndex() + "");
            }
            NumTF.setEnabled(false);
        } else {
            PokemonFormCB.setEnabled(false);
            NumTF.setEnabled(true);
        }
    }//GEN-LAST:event_AltFormCBActionPerformed

    private void GendLessCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GendLessCBActionPerformed
        if (!GendLessCB.isSelected()) {
            MaleChanceSp.setEnabled(true);
        } else {
            MaleChanceSp.setEnabled(false);
        }
    }//GEN-LAST:event_GendLessCBActionPerformed

    private void NewBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewBtActionPerformed
        if (question("Are you sure?")) {
            NumTF.setText((index.dexSize() + 1) + "");
            NameTF.setText("");
            PokeLabelTF.setText("---New---");
            SpeciesTF.setText("");
            TypeACB.setSelectedIndex(0);
            TypeBCB.setSelectedIndex(0);
            TypeCCB.setSelectedIndex(0);
            HPSp.setValue(100);
            AtkSp.setValue(100);
            DefSp.setValue(100);
            SpaSp.setValue(100);
            SpdSp.setValue(100);
            SpeSp.setValue(100);
            AbilityACB.setSelectedIndex(0);
            AbilityBCB.setSelectedIndex(0);
            AbilityHCB.setSelectedIndex(0);
            EvolveCB.setSelectedIndex(0);
            ConditionCB.setSelectedIndex(0);
            EvolveLevelCB.setValue(0);
            EvolveThingCB.setSelectedIndex(0);
            BaseExpSp.setValue(0);
            HPEVSp.setValue(0);
            AtkEVSp.setValue(0);
            DefEVSp.setValue(0);
            SpaEVSp.setValue(0);
            SpdEVSp.setValue(0);
            SpeEVSp.setValue(0);
            CptRtSp.setValue(0);
            GrwRtCB.setSelectedIndex(0);
            GendLessCB.setSelected(false);
            MaleChanceSp.setValue(0);
            EggNmbSp.setValue(0);
            EggGrACB.setSelectedIndex(0);
            EggGrBCB.setSelectedIndex(0);
            ItemCB.setSelectedIndex(0);
            ItemPrctSp.setValue(0);
            AltFormCB.setSelected(false);
            PokemonFormCB.setSelectedIndex(0);
            DescrTA.setText("");
            DescrTwoTA.setText("");
        }
        this.repaint();
    }//GEN-LAST:event_NewBtActionPerformed

    private void PokemonFormCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PokemonFormCBActionPerformed
        if (PokemonFormCB.isEnabled()) {
            PokemonBase temp = (PokemonBase) PokemonFormCB.getSelectedItem();
            NumTF.setText(temp.getIndex() + "");
        }
    }//GEN-LAST:event_PokemonFormCBActionPerformed

    private void MoveMakerBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveMakerBtActionPerformed
        movemaker.setVisible(true);
    }//GEN-LAST:event_MoveMakerBtActionPerformed

    private void LoadBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadBtActionPerformed
        setPokemon((PokemonBase) PokeListCB.getSelectedItem());
        repaint();
    }//GEN-LAST:event_LoadBtActionPerformed

    private void DeleteBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtActionPerformed
        index.deletePokemon((PokemonBase) PokeListCB.getSelectedItem());
        repaint();
    }//GEN-LAST:event_DeleteBtActionPerformed

    private void SortBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortBtActionPerformed
        index.sortDexNumber();
        repaint();
    }//GEN-LAST:event_SortBtActionPerformed

    public void setPokemon(PokemonBase poke) {
        if (question("Are you sure?")) {
            NumTF.setText("" + poke.getIndex());
            NameTF.setText(poke.getName());
            PokeLabelTF.setText(NameTF.getText());
            SpeciesTF.setText(poke.getSpecies());
            TypeACB.setSelectedItem(poke.getType(1));
            TypeBCB.setSelectedItem(poke.getType(2));
            TypeCCB.setSelectedItem(poke.getType(3));
            HPSp.setValue(poke.getHP());
            AtkSp.setValue(poke.getAtk());
            DefSp.setValue(poke.getDef());
            SpaSp.setValue(poke.getSpA());
            SpdSp.setValue(poke.getSpD());
            SpeSp.setValue(poke.getSpe());
            AbilityACB.setSelectedItem(poke.getAbility(1));
            AbilityBCB.setSelectedItem(poke.getAbility(2));
            AbilityHCB.setSelectedItem(poke.getAbility(3));
            EvolveCB.setSelectedItem(poke.getPreevolution());
            ConditionCB.setSelectedItem(poke.getCondition());
            EvolveLevelCB.setValue(poke.getEvolveLevel());
            EvolveThingCB.setSelectedItem(poke.getEvolveThing());
            BaseExpSp.setValue(poke.getBaseExp());
            HPEVSp.setValue(poke.getEvs(1));
            AtkEVSp.setValue(poke.getEvs(2));
            DefEVSp.setValue(poke.getEvs(3));
            SpaEVSp.setValue(poke.getEvs(4));
            SpdEVSp.setValue(poke.getEvs(5));
            SpeEVSp.setValue(poke.getEvs(6));
            CptRtSp.setValue(poke.getCaptureRate());
            GrwRtCB.setSelectedItem(poke.getGrowthRate());
            if (poke.getGender() == -1) {
                GendLessCB.setSelected(true);
            } else {
                GendLessCB.setSelected(false);
                MaleChanceSp.setValue(poke.getGender());
            }
            EggNmbSp.setValue(poke.getEggNumber());
            EggGrACB.setSelectedItem(poke.getEggGroup(1));
            EggGrBCB.setSelectedItem(poke.getEggGroup(2));
            ItemCB.setSelectedItem(poke.getItem());
            ItemPrctSp.setValue(poke.getItemChance());
            if (poke.getAlternativeForm() == null) {
                AltFormCB.setSelected(false);
                PokemonFormCB.setSelectedItem(poke);
                PokemonFormCB.setEnabled(false);
            } else {
                AltFormCB.setSelected(true);
                PokemonFormCB.setSelectedItem(poke.getAlternativeForm());
                PokemonFormCB.setEnabled(true);
            }
            DescrTA.setText(poke.getDescription(1));
            DescrTwoTA.setText(poke.getDescription(2));
        }
    }

    public static boolean question(String quest) {
        return JOptionPane.showConfirmDialog(null, quest, "Question", JOptionPane.YES_NO_OPTION) == 0;
    }

    @Override
    public void repaint() {
        Object temp = PokemonFormCB.getSelectedItem();
        PokemonFormCB.setModel(new javax.swing.DefaultComboBoxModel(index.getArray()));
        PokemonFormCB.setSelectedItem(temp);
        temp = EvolveCB.getSelectedItem();
        EvolveCB.setModel(new javax.swing.DefaultComboBoxModel(index.getArray()));
        EvolveCB.setSelectedItem(temp);
        temp = PokeListCB.getSelectedItem();
        PokeListCB.setModel(new javax.swing.DefaultComboBoxModel(index.getArray()));
        PokeListCB.setSelectedItem(temp);
        super.repaint();
    }

    @Override
    public void dispose() {
        index.saveList("save.txt");
        System.exit(0);
    }

    private class StatMeter extends javax.swing.JPanel {

        public int length, start;

        @Override
        public void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;

            for (int i = 1; i <= 6; i++) {
                javax.swing.JSpinner spin = HPSp;

                length = (TypeCCB.getWidth() + TypeCCB.getX()) - (HPSp.getX() + HPSp.getWidth()) - 5;
                start = HPSp.getX() + HPSp.getWidth() + 5;

                switch (i) {
                    case 1:
                        spin = HPSp;
                        break;
                    case 2:
                        spin = AtkSp;
                        break;
                    case 3:
                        spin = DefSp;
                        break;
                    case 4:
                        spin = SpaSp;
                        break;
                    case 5:
                        spin = SpdSp;
                        break;
                    case 6:
                        spin = SpeSp;
                        break;
                }

                Color hue = Color.getHSBColor((float) spin.getValue().hashCode() / 255 * 5 / 7, 1f, 1f);

                g2d.setColor(hue);
                g2d.fill(new Rectangle(start, spin.getY(),
                        (int) ((float) length * spin.getValue().hashCode() / 255) + 2, 22));
                g2d.setColor(Color.BLACK);
                g2d.drawRect(start, spin.getY(),
                        (int) ((float) length * spin.getValue().hashCode() / 255) + 1, 21);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AbilityACB;
    private javax.swing.JComboBox AbilityBCB;
    private javax.swing.JComboBox AbilityHCB;
    private javax.swing.JCheckBox AltFormCB;
    private javax.swing.JSpinner AtkEVSp;
    private javax.swing.JSpinner AtkSp;
    private javax.swing.JSpinner BaseExpSp;
    private javax.swing.JLabel CondThingL;
    private javax.swing.JComboBox ConditionCB;
    private javax.swing.JSpinner CptRtSp;
    private javax.swing.JPanel DeepStatsP;
    private javax.swing.JSpinner DefEVSp;
    private javax.swing.JSpinner DefSp;
    private javax.swing.JButton DeleteBt;
    private javax.swing.JTextArea DescrTA;
    private javax.swing.JTextArea DescrTwoTA;
    private javax.swing.JComboBox EggGrACB;
    private javax.swing.JComboBox EggGrBCB;
    private javax.swing.JSpinner EggNmbSp;
    private javax.swing.JComboBox EvolveCB;
    private javax.swing.JSpinner EvolveLevelCB;
    private javax.swing.JComboBox EvolveThingCB;
    private javax.swing.JCheckBox GendLessCB;
    private javax.swing.JComboBox GrwRtCB;
    private javax.swing.JSpinner HPEVSp;
    private javax.swing.JSpinner HPSp;
    private javax.swing.JComboBox ItemCB;
    private javax.swing.JSpinner ItemPrctSp;
    private javax.swing.JButton LoadBt;
    private javax.swing.JSpinner MaleChanceSp;
    private javax.swing.JButton MoveMakerBt;
    private javax.swing.JTextField NameTF;
    private javax.swing.JButton NewBt;
    private javax.swing.JTextField NumTF;
    private javax.swing.JTextField PokeLabelTF;
    private javax.swing.JComboBox PokeListCB;
    private javax.swing.JComboBox PokemonFormCB;
    private javax.swing.JButton SaveBt;
    private javax.swing.JButton SortBt;
    private javax.swing.JSpinner SpaEVSp;
    private javax.swing.JSpinner SpaSp;
    private javax.swing.JSpinner SpdEVSp;
    private javax.swing.JSpinner SpdSp;
    private javax.swing.JSpinner SpeEVSp;
    private javax.swing.JSpinner SpeSp;
    private javax.swing.JTextField SpeciesTF;
    private javax.swing.JButton SpriteBt;
    private javax.swing.JButton SpriteBt1;
    private javax.swing.JPanel StatsP;
    private javax.swing.JComboBox TypeACB;
    private javax.swing.JComboBox TypeBCB;
    private javax.swing.JComboBox TypeCCB;
    private javax.swing.JButton TypeCalcBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
