/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PokeMaker;

import java.io.BufferedReader;
import java.io.FileReader;

/**
 *
 * @author Wojtek
 */
public class TypeChecker extends javax.swing.JFrame {

    /**
     * Creates new form DmgCalc
     */
    public static String[] type = new String[]{"", "Normal", "Fight", "Grass", "Water",
        "Fire", "Bug", "Flying", "Rock", "Ground", "Poison", "Electric",
        "Ice", "Steel", "Psychic", "Ghost", "Dark", "Light", "Dragon"};

    private float[][] typeTab;

    public TypeChecker() {
        this.typeTab = new float[18][18];
        initComponents();
        try {
            BufferedReader file = new BufferedReader(new FileReader("src/Res/type.txt"));
            String line;
            int j = 0;
            while ((line = file.readLine()) != null) {
                String[] tab = line.split(";");
                for (int i = 0; i < tab.length; i++) {
                    typeTab[i][j] = Float.parseFloat(tab[i]);
                }
                j++;
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        AttackType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        FirstType = new javax.swing.JComboBox();
        SecondType = new javax.swing.JComboBox();
        ThirdType = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Summary = new javax.swing.JTextField();
        RefreshBt = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        OneL = new javax.swing.JLabel();
        TwoL = new javax.swing.JLabel();
        ThreeL = new javax.swing.JLabel();
        FiveL = new javax.swing.JLabel();
        SixL = new javax.swing.JLabel();
        SevenL = new javax.swing.JLabel();
        EightL = new javax.swing.JLabel();
        NineL = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        AttackType.setModel(new javax.swing.DefaultComboBoxModel(type));
        AttackType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeType(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/right.png"))); // NOI18N

        FirstType.setModel(new javax.swing.DefaultComboBoxModel(type));
        FirstType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeType(evt);
            }
        });

        SecondType.setModel(new javax.swing.DefaultComboBoxModel(type));
        SecondType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeType(evt);
            }
        });

        ThirdType.setModel(new javax.swing.DefaultComboBoxModel(type));
        ThirdType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeType(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/right.png"))); // NOI18N

        Summary.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Summary.setText("x1");
        Summary.setFocusable(false);

        RefreshBt.setText("Refresh");
        RefreshBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AttackType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FirstType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Summary, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RefreshBt))
                    .addComponent(ThirdType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondType, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AttackType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Summary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RefreshBt))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecondType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThirdType)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        OneL.setForeground(new java.awt.Color(0, 0, 255));
        OneL.setText("x8 : ");

        TwoL.setForeground(new java.awt.Color(255, 0, 0));
        TwoL.setText("x4 : ");

        ThreeL.setForeground(new java.awt.Color(255, 153, 0));
        ThreeL.setText("x2 : ");

        FiveL.setForeground(new java.awt.Color(0, 204, 0));
        FiveL.setText("x1 : ");

        SixL.setForeground(new java.awt.Color(0, 204, 153));
        SixL.setText("x0.5 : ");

        SevenL.setForeground(new java.awt.Color(0, 102, 102));
        SevenL.setText("x0.25 : ");

        EightL.setForeground(new java.awt.Color(51, 51, 51));
        EightL.setText("x0.125 : ");

        NineL.setText("x0 : ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OneL)
                    .addComponent(TwoL)
                    .addComponent(ThreeL)
                    .addComponent(FiveL)
                    .addComponent(SixL)
                    .addComponent(SevenL)
                    .addComponent(EightL)
                    .addComponent(NineL))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OneL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TwoL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ThreeL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiveL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SixL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SevenL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EightL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NineL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeType(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeType
        float sum = 1;
        String att = AttackType.getSelectedItem().toString();
        sum *= typeEffect(att, FirstType.getSelectedItem().toString());
        sum *= typeEffect(att, SecondType.getSelectedItem().toString());
        sum *= typeEffect(att, ThirdType.getSelectedItem().toString());
        if (sum >= 1 || sum == 0) {
            Summary.setText("x" + ((int) sum));
        } else {
            Summary.setText("x" + sum);
        }
        research();
        this.repaint();
    }//GEN-LAST:event_changeType

    private void RefreshBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshBtActionPerformed
        FirstType.setSelectedIndex(0);
        SecondType.setSelectedIndex(0);
        ThirdType.setSelectedIndex(0);
        research();
        repaint();
    }//GEN-LAST:event_RefreshBtActionPerformed

    public float typeEffect(String att, String def) {
        if (att.equals("") || def.equals("")) {
            return 1;
        } else {
            int a = 0;
            int d = 0;
            for (int i = 1; i < type.length; i++) {
                if (att.equals(type[i])) {
                    a = i - 1;
                }
            }
            for (int i = 1; i < type.length; i++) {
                if (def.equals(type[i])) {
                    d = i - 1;
                }
            }
            return typeTab[d][a];
        }
    }

    public void research() {
        String[] list = new String[]{"x8 : ", "x4 : ", "x2 : ", "x1 : ", "x0.5 : ", "x0.25 : ", "x0.125 : ", "x0 : "};

        for (int i = 1; i < type.length; i++) {
            float sum = 1;
            String att = type[i];
            sum *= typeEffect(att, FirstType.getSelectedItem().toString());
            sum *= typeEffect(att, SecondType.getSelectedItem().toString());
            sum *= typeEffect(att, ThirdType.getSelectedItem().toString());

            if (sum == 8) 
                list[0] += type[i] + " ";
            else if (sum == 4)
                list[1] += type[i] + " ";
            else if (sum == 2)
                list[2] += type[i] + " ";
            else if (sum == 1)
                list[3] += type[i] + " ";
            else if (sum == 0.5)
                list[4] += type[i] + " ";
            else if (sum == 0.25)
                list[5] += type[i] + " ";
            else if (sum == 0.125)
                list[6] += type[i] + " ";
            else if (sum == 0)
                list[7] += type[i] + " ";
        }
        
        OneL.setText(list[0]); TwoL.setText(list[1]); ThreeL.setText(list[2]);
        FiveL.setText(list[3]); SixL.setText(list[4]); SevenL.setText(list[5]);
        EightL.setText(list[6]); NineL.setText(list[7]);
    }

    @Override
    public void dispose() {
        this.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AttackType;
    private javax.swing.JLabel EightL;
    private javax.swing.JComboBox FirstType;
    private javax.swing.JLabel FiveL;
    private javax.swing.JLabel NineL;
    private javax.swing.JLabel OneL;
    private javax.swing.JButton RefreshBt;
    private javax.swing.JComboBox SecondType;
    private javax.swing.JLabel SevenL;
    private javax.swing.JLabel SixL;
    private javax.swing.JTextField Summary;
    private javax.swing.JComboBox ThirdType;
    private javax.swing.JLabel ThreeL;
    private javax.swing.JLabel TwoL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
